# Generated by Django 5.2.6 on 2026-01-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('frequency', models.IntegerField()),
                ('years', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('university', models.CharField(max_length=60)),
                ('course', models.CharField(max_length=60)),
                ('department', models.CharField(max_length=60)),
                ('semester', models.SmallIntegerField()),
                ('subject', models.CharField(max_length=60)),
                ('topic', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'sora_questions',
            },
        ),
    ]
